jupyterhub/jupyter-remote-desktop-proxy

README.md
Closes https://github.com/jupyterhub/team-compass/issues/372
This renames the repository with the proposal in https://github.com/jupyterhub/team-compass/issues/372#issuecomment-773306829. It doesn't rename the Python package.
Also changed the master to main in the README, though the repo branch still needs to be renamed- after transferring the repo I can no longer administer the repo.
=> Rename repo jupyter-desktop-server ➡️  jupyter-remote-desktop-proxy

.github/workflows/publish.yml
Copied from https://github.com/jupyterhub/jupyterhub-idle-culler/pull/19
This will require `secrets.pypi_password` to be added.
I've got access to the [PyPI repo](https://pypi.org/project/jupyter-desktop-server/) so I'm able to create a secret, but can't add it to this repo....
=> Add pypi publish workflow

.github/workflows/binder-badge.yaml
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/8 didn't work:
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/6/checks?check_run_id=2418322936
Try `pull-requests: write` instead
=> binder-badge workflow needs permissions.pull-requests:write

Dockerfile
Update TurboVNC from 2.2.5 to 2.2.6 (latest)
=> Update TurboVNC to 2.2.6

README.md
OpenGL is currently not supported, and we should
document this in the README. 
I hope this is not considered to be blocked by
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/12
=> Add a section on limitations

.github/dependabot.yaml
Don't merge this before #23 so that we don't get dependabots version bumps that is already done in #23.
=> maint: add dependabot for github actions

environment.yml, jupyter_desktop/share/web/noVNC-1.2.0/vnc_lite.html, jupyter_desktop/share/web/novnc-vnc_lite.html.patch
Adds a textarea that acts as a shared bi-directional clipboard. This is based on `vnc.html`:
- https://github.com/novnc/noVNC/blob/v1.2.0/vnc.html#L143-L157
- https://github.com/novnc/noVNC/blob/v1.2.0/app/ui.js#L924-L966
=> Add a shared clipboard

jupyter_remote_desktop_proxy/share/xstartup
This allows xstartup to work with environment where dbus-launch is in PATH while not installed in standard /usr/bin.
=> Remove "/usr/bin" prefix in front of dbus-launch in xstartup

jupyter_remote_desktop_proxy/__init__.py
The extension currently looks first is the executable `vncserver` is available in `PATH`. If it is, this what the extension will use and otherwise the extension the tigervnc bundled with the package.
The arguments (i.e.: `vnc_args`) provided to `vncserver` executable are also determined based on wether the executable comes from the system or the package bundle. However, it is possible that the `vncserver` provided by the system is also TigerVNC and that it could benefits from the same arguments as when using the bundled `vncserver`.
This PR splits that logic in two. First, we determine if `vncserver` can be provided by the system, then we determine if `vncserver` is TigerVNC or something else. Determining if `vncserver` is TigerVNC is a simple matter of looking for a string inside the …
=> Add logic to determine if vncserver is TigerVNC

jupyter_remote_desktop_proxy/__init__.py
In a multi-user environment, the display number and the port cannot have to be selected based on what is available. For the display number, vncserver uses the next free display number when unspecified. As for the port number for websockify, we let jupyter-server-proxy logic finds one for us.
Fix #18
=> Remove hardcoded display number and port, avoids multi-user conflicts

.github/workflows/binder-badge.yaml
Use an action to comment once and update the comment instead of repeatedly commenting.
See https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/2#issuecomment-775461687
This action should ensure there's only one comment that gets updated.
=> Quieten binder-badge bot

CHANGELOG.md
Our changelog didn't have entries for what had changed for these versions, so I backfilled them!
=> Backfill changelog for 1.0.0 and 0.1.3

.github/workflows/release.yaml
I've added the appropriate knobs to PyPI to trust this workflow.
=> Use trusted publishing to push to PyPI

.github/workflows/release.yaml
Copied workflow from
https://github.com/jupyterhub/jupyterhub-python-repo-template/blob/main/.github/workflows/release.yaml
This also bumps up our python version, but given this is a pure wheel we are fine.
=> Fix permissions required for trusted workflow

README.md
Fixes https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/47
=> Document needing seccomp=unconfined

Dockerfile
- Don't run apt-get upgrade, is not necessary
- Use tigervnc from apt rather than what we turbovnc. This allows the image to work on ARM machines as well as getting us a newer version of everything. Also it's possible that TurboVNC doesn't work right now, see #54 
- Reorder and use COPY --chown to make rapid development faster with better caching
- Remove firefox install from apt, as that no longer works anyway (it' a snap). That's set up with https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/51 correctly.
=> Simplify developmental dockerfile

jupyter_remote_desktop_proxy/__init__.py
User can override the default provided xstartup by providing their own in the standard location ~/.vnc/xstartup. We also remove the prescribed geometry to let the user define its own using vnc config or the session manager.
=> Let user defines its own xstartup and geometry

jupyter_remote_desktop_proxy/__init__.py
I originally got the wrong function name for expanding user path.
https://docs.python.org/3/library/os.path.html#os.path.expanduser
=> Fix module 'posixpath' has no attribute 'expand'

jupyter_remote_desktop_proxy/share/xstartup
Reverts jupyterhub/jupyter-remote-desktop-proxy#59
This actually prevents XFCE4 from starting.
=> Revert "Simplify xtartup command"

.github/workflows/build.yaml, .github/workflows/test.yaml, Dockerfile, README.md
The Dockerfile currently fails to build as there's no `jovyan` group (`$NB_GID` corresponds to the `users` group).
Also switches to quay.io for the base image, and uses environment.yml to install as many dependencies as possible from conda-forge. We need it for websockify so might as well use it for everything.
=> Fix container build

Dockerfile
This should prevent the screen from being locked with an unknown password
Closes https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/75
=> Remove xfce4-screensaver

Dockerfile, js/index.js, jupyter-config/jupyter_notebook_config.d/jupyter_remote_desktop_proxy.json, jupyter-config/jupyter_server_config.d/jupyter_remote_desktop_proxy.json, jupyter_remote_desktop_proxy/__init__.py, jupyter_remote_desktop_proxy/handlers.py, jupyter_remote_desktop_proxy/server_extension.py, jupyter_remote_desktop_proxy/setup_websockify.py, jupyter_remote_desktop_proxy/templates/index.html, setup.py
Based on https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/78
I wanted to provide a "Hub Control Panel" menu item only when running in
a JupyterHub. To do this, we need to figure out *when* we are running in
a JupyterHub. There were two ways to do this:
1. Expose an API endpoint as a Jupyter Server extension, and then talk to this
from a purely static JS code to figure out if we were on the hub, and if so,
where the hub control panel is
2. Render the *html* as a jinja2 template from a Jupyter Server extension, leaving
websockify for jupyter-server-proxy to handle
After some poking around (and trying a 3rd approach that's more complex), (2) seems
the right path. 
A "Hub Control Panel" button is now added if we are running inside a hub,
but *not* added if we are *not* running …
=> Add a "Hub Control Panel" menu item if running inside a JupyterHub

Dockerfile
This is the default terminal font, and when not
installed, everything just renders weird.
EDIT by Erik: Closes #85 as its an alternative way of solving the same thing
=> [Docker image] Install fonts-dejavu for use by terminals

.github/workflows/release.yaml, .github/workflows/test.yaml, Dockerfile
This PR updates the Dockerfile so that it can build to include TigerVNC (default) or TurboVNC by passing `--build-arg vncserver=turbovnc`. It then automates a build and publishing of an image in two variants:
- `quay.io/jupyterhub/jupyter-remote-desktop-proxy:<version>` (the same as `-tigervnc`)
- `quay.io/jupyterhub/jupyter-remote-desktop-proxy:<version>-tigervnc`
- `quay.io/jupyterhub/jupyter-remote-desktop-proxy:<version>-turbovnc`
- Fixes #88
Provides multi arch images, Amd64 and Arm64
- Fixes #68
In a very primitive way though, where I think #93 improves on testing beyond this basic check
=> Publish TigerVNC and TurboVNC image to quay.io

.github/workflows/release.yaml
This is a followup to #94 where I used a syntax for a github action that changed since the PR was written initially (from `<empty-string>` to `""` to represent an empty string).
=> Fix automation to publish tigervnc and turbovnc images

setup.py
We don't have tests to verify things work with old versions of jupyter-server-proxy, so it feels good to enforce something new now that we are about to release a new major version.
=> Require jupyter-server-proxy 4+

jupyter_remote_desktop_proxy/setup_websockify.py
I think we checked the case sensitive TigerVNC string which works if TigerVNC was installed via `apt`, but may not work when installed in another way. On the other hand, at those times, checking for the case insensitive string would work then. So, this PR makes the check case insensitive.
- Fixes #69
Thank you @goekce for your thorough issue report!!
=> Fix TigerVNC detection for non-apt installations

jupyter_remote_desktop_proxy/setup_websockify.py
Without specifying a port for TurboVNC, we will fail to wrap it I think. jupyter-server-proxy will proxy to the port websockify listens to, and websockify is configure to listen to `{port}` correctly, but I think this port must be the same what is to be wrapped - otherwise it won't wrap that specific bind I think. Note that all examples include specifying websockify port for the wrapped command as well (or know it and match it without specifying it to match).
With this, things work - without it it doesn't for TurboVNC.
- Fixes #54
Debugged in https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/98#issuecomment-1985044545. I've tested this to resolve #54 manually.
=> Fix failure to specify port for TurboVNC server

MANIFEST.in
The templates directory includes the index.html which is rendered by handlers.py. Without the index.html file it throws a 500 error.
=> MANIFEST.in: Include templates/ directory

.github/workflows/test.yaml
This is work done in parallell to #93, initially thought to be a quick fix to ensure TurboVNC also works. Like @yuvipanda in #93 I ran into issues with different behavior locally and within the GitHub actions environment, but think the biggest difference got resolved by providing a TTY device.
@yuvipanda I propose #93 is completed in a dedicated job inside the test.yaml workflow, side by side to the image-test job finalized in this PR - and then finally in an optional dedicated PR we prune misc bash things I've done in favor of python things you've done.
I consider this to fix #98, which was bugfixed by #99 but not tested by automation to make it work as it is now to some extent at least.
- added test for TurboVNC image in parallel to test for TigerVNC image
- added `websockify --help` …
=> Fix image tests: vncserver, websockify, jupyter-remote-desktop-proxy

CHANGELOG.md
- Fixes #87 
Release planned for tuesday 2nd April if approved. Note that I've self-merged to expedite this and offload my work week:
- #101
- #104
- #107
=> Add changelog for v2.0.0

js/index.js
Sometimes the initial websocket connection fails. This is a workaround that tries to connect a few times with some delay in between connection attempts when a request fails.
Relates to https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/105. Although it doesn't solve the actual underlying issue, I think it's a reasonable fix from a UX point of view.
Here's a video of the patch in action:
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/assets/1142203/81c5210e-5384-45e8-9549-c72a4b484775
=> Retry a few times when the initial connection fails

js/clipboard.css, js/clipboard.js, js/index.js, jupyter_remote_desktop_proxy/templates/index.html
The original JavaScript is based on a tooltip example https://github.com/jupyterhub/jupyter-remote-desktop-proxy/blob/d702e1a68f1ffee0fab57dbbefb1c11b36c48776/js/tooltip.js#L4
but it's been modified so the naming is misleading.
=> Rename tooltip to clipboard

js/index.js, package.json
1.4.0 has two copies of `rfb.js`
- `node_modules/@novnc/novnc/core/rfb.js`
- `node_modules/@novnc/novnc/lib/rfb.js`
1.5.0 only has one copy:
- `node_modules/@novnc/novnc/lib/rfb.js`
- https://github.com/novnc/noVNC/commit/b35cf6dd1253142267f68f052986d0560f7a495c
Closes https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/117
=> Update to use novnc 1.5.0

js/clipboard.js, js/index.js, tests/test_browser.py
I think it's more natural for the clipboard to automatically close when you click the desktop outside it, e.g. to paste something into the desktop. Currently you have to click the button again to close it.
=> Close clipboard if clicked outside

.github/dependabot.yaml, Dockerfile
This ensures we control the OS/Python/Jupyter/XFCE/VNC versions
=> Pin dockerfile SHA, bump monthly with dependabot

Dockerfile
Needed due to https://github.com/jupyter/docker-stacks/pull/2172
Closes https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/135
=> Switch to date tag for base image, install nodejs

package.json
novnc 1.6.0 was released 4 days ago, and with it it seems we have a JS build failure when running `npm run webpack`. Not functioning with 1.6.0 is tracked by #141.
=> Pin js dependency novnc to 1.5.0 until we support 1.6.0

README.md, jupyter_remote_desktop_proxy/setup_websockify.py
Defines the variable `JUPYTER_REMOTE_DESKTOP_PROXY_XSTARTUP` to launch a custom xstartup script.
The main benefit of this is launching a different desktop e.g. https://github.com/manics/jupyter-desktop-mate/blob/main/start-mate.sh on a system where a user's home directory may be mounted, meaning `~/.vnc/xstartup` doesn't exist.
Ideally this would be done with a traitlets configuration so it could be specified in one of the standard configuration paths, but the VNC server and desktop are launched using a custom jupyter-server-proxy entrypoint
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/blob/4f68d135bde2bc06dd59762d4c70565c031ac34d/setup.py#L62-L64
so as far as I know it's not possible to pass a traitlets configuration object to it.
=> Override xstartup with environment variable `JUPYTER_REMOTE_DESKTOP_PROXY_XSTARTUP`

.github/workflows/test.yaml, README.md, jupyter_remote_desktop_proxy/setup_websockify.py
By exposing the TurboVNC vncserver with a unix socket file, created by jupyter-server-proxy with read/write permissions only for the current unix user, TurboVNC becomes suitable for example in the-littlest-jupyterhub deployments. The key difference is that multiple users can run their own VNC servers now without exposing it to other users, as a unix socket file compared to a TCP port, comes with user specific permissions.
This requires TurboVNC 3.1.0 and is due to this a breaking change worth highlighting in a major release.
From the [3.1 beta.1 changelog](https://github.com/TurboVNC/turbovnc/blob/38dbbf30fd179621d2ee8578ed924fe09c9ef203/ChangeLog.md?plain=1#L424C1-L432C28):
> 6. The TurboVNC Server can now listen on a Unix domain socket, rather than a
TCP port, for connections from VNC …
=> Access TurboVNC via a unix socket instead of a port

CHANGELOG.md
- closes #125, which became outdated
I have written the preliminary date for the v3.0.0 release for 19th March (tomorrow).
To address @manics review comment in https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/125/files#r1684089648, I pushed [dd81df5](https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/148/commits/dd81df5b9c2ab88cf8b6cc7bd805097eff7fc7f5).
=> Add changelog for v3.0.0

.github/workflows/test.yaml, .gitignore, jupyter_remote_desktop_proxy/setup_websockify.py
With 3.0.0, we claimed that UNIX sockets would be used instead of TCP ports, but when using TigerVNC its TCP port remained open because we didn't explicitly disable it as was needed.
This is a patch for that, addressing https://github.com/jupyterhub/jupyter-remote-desktop-proxy/security/advisories/GHSA-vrq4-9hc3-cgp7.
=> Ensure TigerVNC isn't accessible via the network
